# Generated by Django 4.2.4 on 2023-08-13 15:31

import ckeditor.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='hero_description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
